spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, aws"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create
    open-in-view: false


# multipart

#spring.servlet.multipart.enabled: true
#spring.servlet.multipart.max-file-size: 10MB
#spring.servlet.multipart.max-request-size: 10MB
