spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, aws"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
